version: "{build}"

# Build only on tags
skip_non_tags: true

environment:
  matrix:
    - ARCH: x64
    - ARCH: x86

matrix:
  fast_finish: true

# Shallow clone cannot be used when using git-submodule
shallow_clone: false

build:
  verbosity: minimal

before_build:
  - 'if /I "%ARCH%"=="x64" (set ARG=amd64) else (set ARG=x86)'
  - 'copy "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include\Win32.Mak" "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include"'
  - 'set SDK_INCLUDE_DIR=C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include'
  - 'call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARG%'
#  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%ARCH% /release' 
  - '"%APPVEYOR_BUILD_FOLDER%\appveyor.bat" install'

build_script:
  - '"%APPVEYOR_BUILD_FOLDER%\appveyor.bat" build'

after_build:
  - '"%APPVEYOR_BUILD_FOLDER%\appveyor.bat" package'

artifacts:
  - path: gvim_*_x86.zip
    name: gVim_x86
  - path: gvim_*_x64.zip
    name: gVim_x64

before_deploy:
  - for /f "delims=" %%i in (gitlog.txt) do set GITLOG=%%i

deploy:
  - provider: GitHub
    description: |
      Vim Windows build

      ### Changes:

      $(GITLOG)

      * [ActivePerl](http://www.activestate.com/activeperl/downloads) 5.24
      * [ActiveTcl](http://www.activestate.com/activetcl/downloads) 8.6
      * [LuaJIT](http://luajit.org/download.html) 2.0.4
      * [Python](https://www.python.org/downloads/) 2.7
      * [Python3](https://www.python.org/downloads/) 3.5
      * [RubyInstaller](http://rubyinstaller.org/downloads/) 2.2

      Make sure that you install the same architecture (32bit/64bit) that matches your Vim installation.
    auth_token:
      # Update the following key, once this is merged to Vim main repository:
      secure: mc4aWw/2hwVLGAoi1LqIzSwQLv24HZ7LL9DxLMtQFRJd2YhnNeyV8e49xNUKAnRZ
    artifact: /gVim/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: false

cache:
  - downloads -> appveyor.bat

# vim: ts=2 sw=2 et
